/**
 * Image manifest for the Reena demo.
 * Only Pexels License / Unsplash License sources. Everything is self-hosted.
 */

const pexels = (id) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=2400`;
const unsplash = (id) => `https://images.unsplash.com/${id}?w=2400&q=85&fm=jpg`;

export const images = [
  {
    name: "hero-coil",
    use: "Hero slide 1 — Stabilizers (LCP)",
    url: pexels(12515072),
    page: "https://www.pexels.com/photo/12515072/",
    credit: "Vadim Timayev",
    licence: "Pexels License",
    position: "55% 50%",
    hero: true,
    alt: unsplash("photo-1707409464255-e78eb873298a"),
  },
  {
    name: "hero-pcb-blue",
    use: "Hero slide 2 — Solar Inverters",
    url: unsplash("photo-1592659762303-90081d34b277"),
    page: "https://unsplash.com/photos/pfR18JNEMv8",
    credit: "Vishnu Mohanan",
    licence: "Unsplash License",
    position: "50% 50%",
    hero: true,
    portraitFrom: pexels(2182863),
    alt: pexels(2182863),
  },
  {
    name: "hero-solar-dusk",
    use: "Hero slide 3 — MPPT & Solar Chargers",
    url: pexels(16586150),
    page: "https://www.pexels.com/photo/16586150/",
    credit: "Diego Vivanco",
    licence: "Pexels License",
    position: "60% 50%",
    hero: true,
    alt: pexels(371917),
  },
  {
    name: "hero-copper-red",
    use: "Hero slide 4 — Electrical Wires",
    url: pexels(28286038),
    page: "https://www.pexels.com/photo/copper-wire-28286038/",
    credit: "Nic Wood",
    licence: "Pexels License",
    position: "45% 50%",
    hero: true,
    alt: pexels(12515072),
  },
  {
    name: "cat-stabilizer",
    use: "Category card — Voltage Stabilizers",
    url: pexels(8108716),
    page: "https://www.pexels.com/photo/8108716/",
    credit: "Mikhail Nilov",
    licence: "Pexels License",
    position: "center",
    alt: unsplash("photo-1631375937044-6dd5beac01d2"),
  },
  {
    name: "cat-inverter",
    use: "Category card — Solar Inverters",
    url: unsplash("photo-1580584126903-c17d41830450"),
    page: "https://unsplash.com/photos/1580584126903",
    credit: "Michael Dziedzic",
    licence: "Unsplash License",
    position: "center",
    alt: pexels(2182863),
  },
  {
    name: "cat-mppt",
    use: "Category card — MPPT & Solar Chargers",
    url: pexels(14673396),
    page: "https://www.pexels.com/photo/14673396/",
    credit: "Jamshaid Anwar",
    licence: "Pexels License",
    position: "center",
    alt: pexels(14673364),
  },
  {
    name: "cat-wires",
    use: "Category card — Electrical Wires",
    url: pexels(28286038),
    page: "https://www.pexels.com/photo/copper-wire-28286038/",
    credit: "Nic Wood",
    licence: "Pexels License",
    position: "center",
    alt: unsplash("photo-1761507320645-b11a00bfcc34"),
  },
  {
    name: "app-village-night",
    use: "Application — Homes",
    url: pexels(37120321),
    page: "https://www.pexels.com/photo/37120321/",
    credit: "Saeed Ahmed Abbasi (Kandiaro, Sindh)",
    licence: "Pexels License",
    position: "50% 60%",
    alt: pexels(11899002),
  },
  {
    name: "app-fridge",
    use: "Application — Refrigerators",
    url: pexels(17386217),
    page: "https://www.pexels.com/photo/17386217/",
    credit: "Moustafa AbdlRazik",
    licence: "Pexels License",
    position: "center",
  },
  {
    name: "app-ac",
    use: "Application — Air Conditioners",
    url: pexels(3964537),
    page: "https://www.pexels.com/photo/3964537/",
    credit: "ready made",
    licence: "Pexels License",
    position: "center",
  },
  {
    name: "app-office",
    use: "Application — Offices",
    url: pexels(15389577),
    page: "https://www.pexels.com/photo/15389577/",
    credit: "Carsten Ruthemann",
    licence: "Pexels License",
    position: "center",
  },
  {
    name: "app-factory",
    use: "Application — Commercial & Industrial",
    url: pexels(34718925),
    page: "https://www.pexels.com/photo/34718925/",
    credit: "Yetkin Ağaç",
    licence: "Pexels License",
    position: "center",
    alt: pexels(32972128),
  },
  {
    name: "app-rooftop-solar",
    use: "Application — Solar Systems",
    url: pexels(14673364),
    page: "https://www.pexels.com/photo/14673364/",
    credit: "Jamshaid Anwar",
    licence: "Pexels License",
    position: "center",
    alt: pexels(14673396),
  },
  {
    name: "bg-tower-night",
    use: "Sun to Socket background",
    url: pexels(27824579),
    page: "https://www.pexels.com/photo/27824579/",
    credit: "Christopher Borges",
    licence: "Pexels License",
    position: "center",
    alt: pexels(11533352),
  },
  {
    name: "mfg-soldering",
    use: "Made by Reena",
    url: pexels(3912983),
    page: "https://www.pexels.com/photo/3912983/",
    credit: "ThisIsEngineering",
    licence: "Pexels License",
    position: "40% 50%",
  },
  {
    name: "mfg-hands",
    use: "Made by Reena",
    url: pexels(35187505),
    page: "https://www.pexels.com/photo/35187505/",
    credit: "Bulat843",
    licence: "Pexels License",
    position: "center",
    alt: pexels(3912981),
  },
  {
    name: "mfg-coils",
    use: "Made by Reena",
    url: pexels(33339861),
    page: "https://www.pexels.com/photo/33339861/",
    credit: "HONG SON",
    licence: "Pexels License",
    position: "center",
    alt: pexels(6069107),
  },
  {
    name: "genuine-pcb",
    use: "Genuine check teaser",
    url: unsplash("photo-1631375937044-6dd5beac01d2"),
    page: "https://unsplash.com/photos/1631375937044",
    credit: "Vishnu Mohanan",
    licence: "Unsplash License",
    position: "center",
    alt: pexels(2182863),
  },
  {
    name: "dealer-shop",
    use: "Dealers page",
    url: pexels(2598290),
    page: "https://www.pexels.com/photo/2598290/",
    credit: "Aadil (Faisalabad)",
    licence: "Pexels License",
    position: "center",
    alt: pexels(15389577),
  },
];

export const WIDTHS = [480, 828, 1200, 1920];
export const PORTRAIT = { w: 1080, h: 1600 };
